/**
 * "Break it down" — Supabase Edge Function
 * Phase 2 — Engines
 *
 * Receives a task and returns a list of suggested sub-tasks generated by Claude Haiku.
 * Sub-tasks have optional due dates spread between today and the main task's due date.
 *
 * Rate limit: 10 breakdowns per user per day (tracked via aiBreakdownAt column).
 *
 * NOTE: This function is never labelled as AI in the UI.
 *
 * Expected request body:
 * {
 *   taskId:    string   — the task to break down
 *   title:     string   — task title
 *   dueDate:   string | null — main task due date (ISO date string or null)
 * }
 *
 * Response:
 * {
 *   subTasks: Array<{ title: string; dueDate: string | null }>
 * }
 */

import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
import Anthropic from 'https://esm.sh/@anthropic-ai/sdk@0.39.0';

const DAILY_LIMIT = 10;

// ─── CORS headers ─────────────────────────────────────────────────────────────

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

// ─── Handler ──────────────────────────────────────────────────────────────────

Deno.serve(async (req: Request) => {
  // Handle CORS preflight
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }

  try {
    // ── 1. Auth: verify the user is signed in ─────────────────────────────────
    const authHeader = req.headers.get('Authorization');
    if (!authHeader) {
      return errorResponse('Missing authorization header', 401);
    }

    const supabase = createClient(
      Deno.env.get('SUPABASE_URL')!,
      Deno.env.get('SUPABASE_ANON_KEY')!,
      { global: { headers: { Authorization: authHeader } } }
    );

    const { data: { user }, error: authError } = await supabase.auth.getUser();
    if (authError || !user) {
      return errorResponse('Unauthorized', 401);
    }

    // ── 2. Parse request body ─────────────────────────────────────────────────
    const body = await req.json();
    const { taskId, title, dueDate } = body as {
      taskId: string;
      title: string;
      dueDate: string | null;
    };

    if (!taskId || typeof taskId !== 'string') {
      return errorResponse('taskId is required', 400);
    }
    if (!title || typeof title !== 'string' || title.trim().length === 0) {
      return errorResponse('title is required', 400);
    }

    // ── 3. Rate limit check: count breakdowns today ───────────────────────────
    const todayMidnight = new Date();
    todayMidnight.setUTCHours(0, 0, 0, 0);

    const { count, error: countError } = await supabase
      .from('tasks')
      .select('id', { count: 'exact', head: true })
      .eq('userid', user.id)
      .eq('aibreakdownused', true)
      .gte('aiBreakdownAt', todayMidnight.toISOString());

    if (countError) {
      return errorResponse('Could not check usage limit', 500);
    }

    if ((count ?? 0) >= DAILY_LIMIT) {
      return errorResponse(
        `You've used all ${DAILY_LIMIT} breakdowns for today. Try again tomorrow.`,
        429
      );
    }

    // ── 4. Build the prompt for Claude Haiku ─────────────────────────────────
    const dueDateContext = dueDate
      ? `The task is due on ${dueDate}.`
      : 'The task has no due date.';

    const prompt = `You are a helpful productivity assistant. Break the following task into clear, actionable sub-tasks.

Task: "${title.trim()}"
${dueDateContext}

Rules:
- Return ONLY a JSON array of sub-task objects. No explanation, no markdown, no extra text.
- Each object must have: "title" (string) and "dueDate" (string in YYYY-MM-DD format, or null).
- If the main task has a due date, spread sub-task due dates evenly between today and that date where it makes sense. Otherwise set dueDate to null.
- Sub-task titles should be short and start with a verb (e.g. "Book venue", "Send invites").
- Generate as many sub-tasks as needed to fully cover the task.

Respond with only valid JSON. Example format:
[
  { "title": "Research options", "dueDate": "2026-04-05" },
  { "title": "Make decision", "dueDate": null }
]`;

    // ── 5. Call Claude Haiku ──────────────────────────────────────────────────
    const anthropic = new Anthropic({
      apiKey: Deno.env.get('ANTHROPIC_API_KEY')!,
    });

    const message = await anthropic.messages.create({
      model: 'claude-haiku-4-5-20251001',
      max_tokens: 1024,
      messages: [{ role: 'user', content: prompt }],
    });

    // Extract the text content from the response
    const responseText = message.content
      .filter((block) => block.type === 'text')
      .map((block) => (block as { type: 'text'; text: string }).text)
      .join('');

    // Strip markdown code fences if Claude wrapped the JSON (e.g. ```json ... ```)
    const jsonText = responseText.replace(/^```(?:json)?\s*/i, '').replace(/\s*```\s*$/, '').trim();

    // Parse the JSON array from the response
    let subTasks: Array<{ title: string; dueDate: string | null }>;
    try {
      subTasks = JSON.parse(jsonText);
      if (!Array.isArray(subTasks)) throw new Error('Response is not an array');
    } catch {
      return errorResponse('Failed to parse sub-tasks from response', 500);
    }

    // Validate each sub-task has the expected shape
    subTasks = subTasks.filter(
      (item) => item && typeof item.title === 'string' && item.title.trim().length > 0
    );

    // ── 6. Mark the task as broken down ──────────────────────────────────────
    await supabase
      .from('tasks')
      .update({
        aibreakdownused: true,
        aiBreakdownAt: new Date().toISOString(),
      })
      .eq('id', taskId)
      .eq('userid', user.id); // RLS double-check

    // ── 7. Return sub-tasks ───────────────────────────────────────────────────
    return new Response(
      JSON.stringify({ subTasks }),
      {
        status: 200,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      }
    );

  } catch (error) {
    const message = error instanceof Error ? error.message : 'Unexpected error';
    return errorResponse(message, 500);
  }
});

// ─── Helper ───────────────────────────────────────────────────────────────────

function errorResponse(message: string, status: number): Response {
  return new Response(
    JSON.stringify({ error: message }),
    {
      status,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    }
  );
}
